id = "windows2000"
name = "Windows 2000"
description = "Windows 2000-inspired light and dark themes for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Lewin Probst<info@emirror.de>"]
repository = "https://github.com/emirror-de/windows2k-zed"
